# Site settings
title: VicRuby
email: contact@vicruby.org
description: Victoria Ruby Users Group
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vicruby.org" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
